### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Youskrpig** [RobotvisionLab/HFENet#1]
Hey, Have you got the access of semi-final dataset of Tianchi-2021-Guangdong-Tile-Detection competition?

**Comment by ZhangZhiHao233** [comment]
只有初赛的数据集

**Comment by deng150** [comment]
您好  有对应的论文吗

**Comment by ZhangZhiHao233** [comment]
> 您好 有对应的论文吗

你好，论文在review中还没发表
